Location.create!([
  { id: 1, name: 'Venezuela', location_type: 'country', parent_location_id: nil, is_active: true},
  { id: 2, name: 'Amazonas', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 3, name: 'Anzoátegui', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 4, name: 'Apure', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 5, name: 'Aragua', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 6, name: 'Barinas', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 7, name: 'Bolívar', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 8, name: 'Carabobo', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 9, name: 'Cojedes', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 10, name: 'Delta Amacuro', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 11, name: 'Falcón', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 12, name: 'Guárico', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 13, name: 'Lara', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 14, name: 'Mérida', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 15, name: 'Miranda', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 16, name: 'Monagas', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 17, name: 'Nueva Esparta', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 18, name: 'Portuguesa', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 19, name: 'Sucre', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 20, name: 'Táchira', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 21, name: 'Trujillo', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 22, name: 'Vargas', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 23, name: 'Yaracuy', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 24, name: 'Zulia', location_type: 'state', parent_location_id: 1, is_active: true},
  { id: 25, name: 'Puerto Ayacucho', location_type: 'city', parent_location_id: 2, is_active: true},
  { id: 26, name: 'Barcelona', location_type: 'city', parent_location_id: 3, is_active: true},
  { id: 27, name: 'Puerto La Cruz', location_type: 'city', parent_location_id: 3, is_active: true},
  { id: 28, name: 'El Tigre', location_type: 'city', parent_location_id: 3, is_active: true},
  { id: 29, name: 'San Fernando de Apure', location_type: 'city', parent_location_id: 4, is_active: true},
  { id: 30, name: 'Guasdualito', location_type: 'city', parent_location_id: 4, is_active: true},
  { id: 31, name: 'Maracay', location_type: 'city', parent_location_id: 5, is_active: true},
  { id: 32, name: 'Cagua', location_type: 'city', parent_location_id: 5, is_active: true},
  { id: 33, name: 'Villa de Cura', location_type: 'city', parent_location_id: 5, is_active: true},
  { id: 34, name: 'Barinas', location_type: 'city', parent_location_id: 6, is_active: true},
  { id: 35, name: 'Socopó', location_type: 'city', parent_location_id: 6, is_active: true},
  { id: 36, name: 'Ciudad Bolívar', location_type: 'city', parent_location_id: 7, is_active: true},
  { id: 37, name: 'Puerto Ordaz', location_type: 'city', parent_location_id: 7, is_active: true},
  { id: 38, name: 'Upata', location_type: 'city', parent_location_id: 7, is_active: true},
  { id: 39, name: 'Valencia', location_type: 'city', parent_location_id: 8, is_active: true},
  { id: 40, name: 'Guacara', location_type: 'city', parent_location_id: 8, is_active: true},
  { id: 41, name: 'Puerto Cabello', location_type: 'city', parent_location_id: 8, is_active: true},
  { id: 42, name: 'San Carlos', location_type: 'city', parent_location_id: 9, is_active: true},
  { id: 43, name: 'Tinaquillo', location_type: 'city', parent_location_id: 9, is_active: true},
  { id: 44, name: 'Tucupita', location_type: 'city', parent_location_id: 10, is_active: true},
  { id: 45, name: 'Coro', location_type: 'city', parent_location_id: 11, is_active: true},
  { id: 46, name: 'Punto Fijo', location_type: 'city', parent_location_id: 11, is_active: true},
  { id: 47, name: 'San Juan de los Morros', location_type: 'city', parent_location_id: 12, is_active: true},
  { id: 48, name: 'Calabozo', location_type: 'city', parent_location_id: 12, is_active: true},
  { id: 49, name: 'Barquisimeto', location_type: 'city', parent_location_id: 13, is_active: true},
  { id: 50, name: 'Carora', location_type: 'city', parent_location_id: 13, is_active: true},
  { id: 51, name: 'Cabudare', location_type: 'city', parent_location_id: 13, is_active: true},
  { id: 52, name: 'Mérida', location_type: 'city', parent_location_id: 14, is_active: true},
  { id: 53, name: 'El Vigía', location_type: 'city', parent_location_id: 14, is_active: true},
  { id: 54, name: 'Los Teques', location_type: 'city', parent_location_id: 15, is_active: true},
  { id: 55, name: 'Guatire', location_type: 'city', parent_location_id: 15, is_active: true},
  { id: 56, name: 'Santa Teresa', location_type: 'city', parent_location_id: 15, is_active: true},
  { id: 57, name: 'Maturín', location_type: 'city', parent_location_id: 16, is_active: true},
  { id: 58, name: 'Punta de Mata', location_type: 'city', parent_location_id: 16, is_active: true},
  { id: 59, name: 'Porlamar', location_type: 'city', parent_location_id: 17, is_active: true},
  { id: 60, name: 'Pampatar', location_type: 'city', parent_location_id: 17, is_active: true},
  { id: 61, name: 'Guanare', location_type: 'city', parent_location_id: 18, is_active: true},
  { id: 62, name: 'Acarigua', location_type: 'city', parent_location_id: 18, is_active: true},
  { id: 63, name: 'Araure', location_type: 'city', parent_location_id: 18, is_active: true},
  { id: 64, name: 'Cumaná', location_type: 'city', parent_location_id: 19, is_active: true},
  { id: 65, name: 'Carúpano', location_type: 'city', parent_location_id: 19, is_active: true},
  { id: 66, name: 'San Cristóbal', location_type: 'city', parent_location_id: 20, is_active: true},
  { id: 67, name: 'Rubio', location_type: 'city', parent_location_id: 20, is_active: true},
  { id: 68, name: 'Táriba', location_type: 'city', parent_location_id: 20, is_active: true},
  { id: 69, name: 'Trujillo', location_type: 'city', parent_location_id: 21, is_active: true},
  { id: 70, name: 'Valera', location_type: 'city', parent_location_id: 21, is_active: true},
  { id: 71, name: 'Boconó', location_type: 'city', parent_location_id: 21, is_active: true},
  { id: 72, name: 'La Guaira', location_type: 'city', parent_location_id: 22, is_active: true},
  { id: 73, name: 'Catia La Mar', location_type: 'city', parent_location_id: 22, is_active: true},
  { id: 74, name: 'San Felipe', location_type: 'city', parent_location_id: 23, is_active: true},
  { id: 75, name: 'Chivacoa', location_type: 'city', parent_location_id: 23, is_active: true},
  { id: 76, name: 'Maracaibo', location_type: 'city', parent_location_id: 24, is_active: true},
  { id: 77, name: 'Cabimas', location_type: 'city', parent_location_id: 24, is_active: true},
  { id: 78, name: 'Ciudad Ojeda', location_type: 'city', parent_location_id: 24, is_active: true},
  { id: 79, name: 'Ville Puerto Ayacucho', location_type: 'town', parent_location_id: 25, is_active: true},
  { id: 80, name: 'Ville Puerto Ayacucho', location_type: 'town', parent_location_id: 25, is_active: true},
  { id: 81, name: 'Ville Puerto Ayacucho', location_type: 'town', parent_location_id: 25, is_active: true},
  { id: 82, name: 'Ville Barcelona', location_type: 'town', parent_location_id: 26, is_active: true},
  { id: 83, name: 'Ville Puerto La Cruz', location_type: 'town', parent_location_id: 27, is_active: true},
  { id: 84, name: 'Ville Puerto La Cruz', location_type: 'town', parent_location_id: 27, is_active: true},
  { id: 85, name: 'Ville El Tigre', location_type: 'town', parent_location_id: 28, is_active: true},
  { id: 86, name: 'Ville San Fernando de Apure', location_type: 'town', parent_location_id: 29, is_active: true},
  { id: 87, name: 'Ville Guasdualito', location_type: 'town', parent_location_id: 30, is_active: true},
  { id: 88, name: 'Ville Maracay', location_type: 'town', parent_location_id: 31, is_active: true},
  { id: 89, name: 'Ville Maracay', location_type: 'town', parent_location_id: 31, is_active: true},
  { id: 90, name: 'Ville Cagua', location_type: 'town', parent_location_id: 32, is_active: true},
  { id: 91, name: 'Ville Cagua', location_type: 'town', parent_location_id: 32, is_active: true},
  { id: 92, name: 'Ville Cagua', location_type: 'town', parent_location_id: 32, is_active: true},
  { id: 93, name: 'Ville Villa de Cura', location_type: 'town', parent_location_id: 33, is_active: true},
  { id: 94, name: 'Ville Barinas', location_type: 'town', parent_location_id: 34, is_active: true},
  { id: 95, name: 'Ville Barinas', location_type: 'town', parent_location_id: 34, is_active: true},
  { id: 96, name: 'Ville Socopó', location_type: 'town', parent_location_id: 35, is_active: true},
  { id: 97, name: 'Ville Socopó', location_type: 'town', parent_location_id: 35, is_active: true},
  { id: 98, name: 'Ville Ciudad Bolívar', location_type: 'town', parent_location_id: 36, is_active: true},
  { id: 99, name: 'Ville Ciudad Bolívar', location_type: 'town', parent_location_id: 36, is_active: true},
  { id: 100, name: 'Ville Ciudad Bolívar', location_type: 'town', parent_location_id: 36, is_active: true},
  { id: 101, name: 'Ville Puerto Ordaz', location_type: 'town', parent_location_id: 37, is_active: true},
  { id: 102, name: 'Ville Upata', location_type: 'town', parent_location_id: 38, is_active: true},
  { id: 103, name: 'Ville Upata', location_type: 'town', parent_location_id: 38, is_active: true},
  { id: 104, name: 'Ville Valencia', location_type: 'town', parent_location_id: 39, is_active: true},
  { id: 105, name: 'Ville Guacara', location_type: 'town', parent_location_id: 40, is_active: true},
  { id: 106, name: 'Ville Puerto Cabello', location_type: 'town', parent_location_id: 41, is_active: true},
  { id: 107, name: 'Ville Puerto Cabello', location_type: 'town', parent_location_id: 41, is_active: true},
  { id: 108, name: 'Ville Puerto Cabello', location_type: 'town', parent_location_id: 41, is_active: true},
  { id: 109, name: 'Ville San Carlos', location_type: 'town', parent_location_id: 42, is_active: true},
  { id: 110, name: 'Ville San Carlos', location_type: 'town', parent_location_id: 42, is_active: true},
  { id: 111, name: 'Ville San Carlos', location_type: 'town', parent_location_id: 42, is_active: true},
  { id: 112, name: 'Ville Tinaquillo', location_type: 'town', parent_location_id: 43, is_active: true},
  { id: 113, name: 'Ville Tucupita', location_type: 'town', parent_location_id: 44, is_active: true},
  { id: 114, name: 'Ville Tucupita', location_type: 'town', parent_location_id: 44, is_active: true},
  { id: 115, name: 'Ville Tucupita', location_type: 'town', parent_location_id: 44, is_active: true},
  { id: 116, name: 'Ville Coro', location_type: 'town', parent_location_id: 45, is_active: true},
  { id: 117, name: 'Ville Punto Fijo', location_type: 'town', parent_location_id: 46, is_active: true},
  { id: 118, name: 'Ville Punto Fijo', location_type: 'town', parent_location_id: 46, is_active: true},
  { id: 119, name: 'Ville Punto Fijo', location_type: 'town', parent_location_id: 46, is_active: true},
  { id: 120, name: 'Ville San Juan de los Morros', location_type: 'town', parent_location_id: 47, is_active: true},
  { id: 121, name: 'Ville San Juan de los Morros', location_type: 'town', parent_location_id: 47, is_active: true},
  { id: 122, name: 'Ville Calabozo', location_type: 'town', parent_location_id: 48, is_active: true},
  { id: 123, name: 'Ville Calabozo', location_type: 'town', parent_location_id: 48, is_active: true},
  { id: 124, name: 'Ville Barquisimeto', location_type: 'town', parent_location_id: 49, is_active: true},
  { id: 125, name: 'Ville Carora', location_type: 'town', parent_location_id: 50, is_active: true},
  { id: 126, name: 'Ville Carora', location_type: 'town', parent_location_id: 50, is_active: true},
  { id: 127, name: 'Ville Cabudare', location_type: 'town', parent_location_id: 51, is_active: true},
  { id: 128, name: 'Ville Mérida', location_type: 'town', parent_location_id: 52, is_active: true},
  { id: 129, name: 'Ville El Vigía', location_type: 'town', parent_location_id: 53, is_active: true},
  { id: 130, name: 'Ville Los Teques', location_type: 'town', parent_location_id: 54, is_active: true},
  { id: 131, name: 'Ville Los Teques', location_type: 'town', parent_location_id: 54, is_active: true},
  { id: 132, name: 'Ville Los Teques', location_type: 'town', parent_location_id: 54, is_active: true},
  { id: 133, name: 'Ville Guatire', location_type: 'town', parent_location_id: 55, is_active: true},
  { id: 134, name: 'Ville Santa Teresa', location_type: 'town', parent_location_id: 56, is_active: true},
  { id: 135, name: 'Ville Santa Teresa', location_type: 'town', parent_location_id: 56, is_active: true},
  { id: 136, name: 'Ville Santa Teresa', location_type: 'town', parent_location_id: 56, is_active: true},
  { id: 137, name: 'Ville Maturín', location_type: 'town', parent_location_id: 57, is_active: true},
  { id: 138, name: 'Ville Maturín', location_type: 'town', parent_location_id: 57, is_active: true},
  { id: 139, name: 'Ville Maturín', location_type: 'town', parent_location_id: 57, is_active: true},
  { id: 140, name: 'Ville Punta de Mata', location_type: 'town', parent_location_id: 58, is_active: true},
  { id: 141, name: 'Ville Punta de Mata', location_type: 'town', parent_location_id: 58, is_active: true},
  { id: 142, name: 'Ville Punta de Mata', location_type: 'town', parent_location_id: 58, is_active: true},
  { id: 143, name: 'Ville Porlamar', location_type: 'town', parent_location_id: 59, is_active: true},
  { id: 144, name: 'Ville Porlamar', location_type: 'town', parent_location_id: 59, is_active: true},
  { id: 145, name: 'Ville Porlamar', location_type: 'town', parent_location_id: 59, is_active: true},
  { id: 146, name: 'Ville Pampatar', location_type: 'town', parent_location_id: 60, is_active: true},
  { id: 147, name: 'Ville Guanare', location_type: 'town', parent_location_id: 61, is_active: true},
  { id: 148, name: 'Ville Guanare', location_type: 'town', parent_location_id: 61, is_active: true},
  { id: 149, name: 'Ville Guanare', location_type: 'town', parent_location_id: 61, is_active: true},
  { id: 150, name: 'Ville Acarigua', location_type: 'town', parent_location_id: 62, is_active: true},
  { id: 151, name: 'Ville Acarigua', location_type: 'town', parent_location_id: 62, is_active: true},
  { id: 152, name: 'Ville Acarigua', location_type: 'town', parent_location_id: 62, is_active: true},
  { id: 153, name: 'Ville Araure', location_type: 'town', parent_location_id: 63, is_active: true},
  { id: 154, name: 'Ville Araure', location_type: 'town', parent_location_id: 63, is_active: true},
  { id: 155, name: 'Ville Araure', location_type: 'town', parent_location_id: 63, is_active: true},
  { id: 156, name: 'Ville Cumaná', location_type: 'town', parent_location_id: 64, is_active: true},
  { id: 157, name: 'Ville Cumaná', location_type: 'town', parent_location_id: 64, is_active: true},
  { id: 158, name: 'Ville Carúpano', location_type: 'town', parent_location_id: 65, is_active: true},
  { id: 159, name: 'Ville San Cristóbal', location_type: 'town', parent_location_id: 66, is_active: true},
  { id: 160, name: 'Ville San Cristóbal', location_type: 'town', parent_location_id: 66, is_active: true},
  { id: 161, name: 'Ville San Cristóbal', location_type: 'town', parent_location_id: 66, is_active: true},
  { id: 162, name: 'Ville Rubio', location_type: 'town', parent_location_id: 67, is_active: true},
  { id: 163, name: 'Ville Táriba', location_type: 'town', parent_location_id: 68, is_active: true},
  { id: 164, name: 'Ville Táriba', location_type: 'town', parent_location_id: 68, is_active: true},
  { id: 165, name: 'Ville Trujillo', location_type: 'town', parent_location_id: 69, is_active: true},
  { id: 166, name: 'Ville Valera', location_type: 'town', parent_location_id: 70, is_active: true},
  { id: 167, name: 'Ville Valera', location_type: 'town', parent_location_id: 70, is_active: true},
  { id: 168, name: 'Ville Valera', location_type: 'town', parent_location_id: 70, is_active: true},
  { id: 169, name: 'Ville Boconó', location_type: 'town', parent_location_id: 71, is_active: true},
  { id: 170, name: 'Ville Boconó', location_type: 'town', parent_location_id: 71, is_active: true},
  { id: 171, name: 'Ville Boconó', location_type: 'town', parent_location_id: 71, is_active: true},
  { id: 172, name: 'Ville La Guaira', location_type: 'town', parent_location_id: 72, is_active: true},
  { id: 173, name: 'Ville La Guaira', location_type: 'town', parent_location_id: 72, is_active: true},
  { id: 174, name: 'Ville La Guaira', location_type: 'town', parent_location_id: 72, is_active: true},
  { id: 175, name: 'Ville Catia La Mar', location_type: 'town', parent_location_id: 73, is_active: true},
  { id: 176, name: 'Ville Catia La Mar', location_type: 'town', parent_location_id: 73, is_active: true},
  { id: 177, name: 'Ville Catia La Mar', location_type: 'town', parent_location_id: 73, is_active: true},
  { id: 178, name: 'Ville San Felipe', location_type: 'town', parent_location_id: 74, is_active: true},
  { id: 179, name: 'Ville San Felipe', location_type: 'town', parent_location_id: 74, is_active: true},
  { id: 180, name: 'Ville Chivacoa', location_type: 'town', parent_location_id: 75, is_active: true},
  { id: 181, name: 'Ville Chivacoa', location_type: 'town', parent_location_id: 75, is_active: true},
  { id: 182, name: 'Ville Maracaibo', location_type: 'town', parent_location_id: 76, is_active: true},
  { id: 183, name: 'Ville Maracaibo', location_type: 'town', parent_location_id: 76, is_active: true},
  { id: 184, name: 'Ville Maracaibo', location_type: 'town', parent_location_id: 76, is_active: true},
  { id: 185, name: 'Ville Cabimas', location_type: 'town', parent_location_id: 77, is_active: true},
  { id: 186, name: 'Ville Ciudad Ojeda', location_type: 'town', parent_location_id: 78, is_active: true},
])

