Model.create!([
                { name: 'Corolla', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'Camry', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'RAV4', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'Hilux', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'Prius', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'Yaris', brand_id: Brand.find_by(name: 'Toyota').id, is_active: true },
                { name: 'Fiesta', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Focus', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Mustang', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Explorer', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Ranger', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Escape', brand_id: Brand.find_by(name: 'Ford').id, is_active: true },
                { name: 'Cruze', brand_id: Brand.find_by(name: 'Chevrolet').id, is_active: true },
                { name: 'Malibu', brand_id: Brand.find_by(name: 'Chevrolet').id, is_active: true },
                { name: 'Spark', brand_id: Brand.find_by(name: 'Chevrolet').id, is_active: true },
                { name: 'Aveo', brand_id: Brand.find_by(name: 'Chevrolet').id, is_active: true },
                { name: 'Trailblazer', brand_id: Brand.find_by(name: 'Chevrolet').id,
                  is_active: true },
                { name: 'Captiva', brand_id: Brand.find_by(name: 'Chevrolet').id, is_active: true },
                { name: 'Civic', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'Accord', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'CR-V', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'Pilot', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'Fit', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'HR-V', brand_id: Brand.find_by(name: 'Honda').id, is_active: true },
                { name: 'Sentra', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'Altima', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'Rogue', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'Versa', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'X-Trail', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'Frontier', brand_id: Brand.find_by(name: 'Nissan').id, is_active: true },
                { name: 'Elantra', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Tucson', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Santa Fe', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Accent', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Kona', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Sonata', brand_id: Brand.find_by(name: 'Hyundai').id, is_active: true },
                { name: 'Rio', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Sportage', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Sorento', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Optima', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Forte', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Soul', brand_id: Brand.find_by(name: 'Kia').id, is_active: true },
                { name: 'Golf', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Jetta', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Tiguan', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Passat', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Polo', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Amarok', brand_id: Brand.find_by(name: 'Volkswagen').id, is_active: true },
                { name: 'Serie 3', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'Serie 5', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'X1', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'X3', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'X5', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'Z4', brand_id: Brand.find_by(name: 'BMW').id, is_active: true },
                { name: 'Clase A', brand_id: Brand.find_by(name: 'Mercedes-Benz').id,
                  is_active: true },
                { name: 'Clase C', brand_id: Brand.find_by(name: 'Mercedes-Benz').id,
                  is_active: true },
                { name: 'Clase E', brand_id: Brand.find_by(name: 'Mercedes-Benz').id,
                  is_active: true },
                { name: 'GLA', brand_id: Brand.find_by(name: 'Mercedes-Benz').id, is_active: true },
                { name: 'GLC', brand_id: Brand.find_by(name: 'Mercedes-Benz').id, is_active: true },
                { name: 'GLE', brand_id: Brand.find_by(name: 'Mercedes-Benz').id, is_active: true }
              ])
